---
format_version: 10
common:
  deploy-task: &deploy-tasks
    - exec:
        command: bash
        arguments:
          -  -c
          -  echo "Deployment on ${ENV_NAME} environment triggered..."
  test-task: &test-tasks
    - exec:
        command: bash
        arguments:
          -  -c
          -  echo "Running tests on ${ENV_NAME} environment triggered..."
    - exec:
        command: bash
        arguments:
          -  -c
          -  docker network create test-automation-setup
    - exec:
        command: bash
        arguments:
          -  -c
          -  docker run -d -p 4444:4444 --net test-automation-setup --name selenium-hub selenium/hub:latest
    - exec:
        command: bash
        arguments:
          -  -c
          -  docker run -d --net test-automation-setup -e HUB_HOST=selenium-hub -v /dev/shm:/dev/shm selenium/node-chrome:latest
    - exec:
        command: bash
        arguments:
          -  -c
          -  docker run -d --net test-automation-setup -e HUB_HOST=selenium-hub -v /dev/shm:/dev/shm selenium/node-firefox:latest
    - exec:
        command: bash
        arguments:
          -  -c
          -  docker run -it --restart=on-failure:3 --network=test-automation-setup --name mvn_test_exec_${ENV_NAME} mvn clean test -Dbrowser=chrome -DgridURL=selenium-hub:4444
    - exec:
        run_if: any
        command: bash
        arguments:
          -  -c
          -  docker rm -f mvn_test_exec_${ENV_NAME}
    - exec:
        run_if: any
        command: bash
        arguments:
          -  -c
          -  docker network rm test-automation-setup
    - exec:
        run_if: failed
        command: bash
        arguments:
          -  -c
          -  send_notification.sh "dev deployment" 1
    - exec:
        run_if: passed
        command: bash
        arguments:
          -  -c
          -  send_notification.sh "dev deployment" 0
pipelines:
  web-tests:
    group: web-tests
    materials:
      mainGit:
        git: https://github.com/MartinsGrinfelds/ui-automation.git
        branch: main
    stages:
      - build:
          jobs:
            build:
              tasks:
              - exec:
                  command: bash
                  arguments:
                    -  -c
                    -  echo "Building..."
      - deploy-stg:
          environment_variables:
            ENV_NAME: STG
          jobs:
            deploy:
              tasks:
                *deploy-tasks
      - test-stg:
          environment_variables:
            ENV_NAME: STG
          jobs:
            test:
              tasks:
                *test-tasks
      - deploy-prd:
          environment_variables:
            ENV_NAME: PRD
          jobs:
            deploy:
              tasks:
                *deploy-tasks
      - test-prd:
          environment_variables:
            ENV_NAME: PRD
          jobs:
            test:
              tasks:
                *test-tasks